name: Update ballerina-dev-website repo

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/scripts'

jobs:
  build:
    runs-on: ubumtu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python Packages
        run: |
          pip install beautifulsoup4
          pip install PyGithub

      - name: Update Ballerina Dev Website
        run: python3 src/scripts/update_html.py
